### ISSUE TITLE
No responses defined for platform: DIALOGFLOW_CONSOLE

### ISSUE THREAD

**Issue by AyhamD** [antonyharfield/webhook-template#1]
Hey 
I am getting this error when i am using:
agent.add(new Suggestion('english'))
after i follow your instructions to deploy locally and this is the output i am getting:

Debugger listening on ws://127.0.0.1:9229/b27847c6-5c62-4052-8548-0ebad674b1a1
For help, see: https://nodejs.org/en/docs/inspector
(node:8820) UnhandledPromiseRejectionWarning: Error: No responses defined for platform: DIALOGFLOW_CONSOLE
    at WebhookClient.send_ (C:\Users\hallo\Desktop\google_home_vocabulary\node_modules\dialogflow-fulfillment\src\dialogflow-fulfillment.js:488:13)
    at C:\Users\hallo\Desktop\google_home_vocabulary\node_modules\dialogflow-fulfillment\src\dialogflow-fulfillment.js:306:38
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
thanks

**Comment by AyhamD** [comment]
Never mind
